# This example for ESP32E-N4 board with built-in IR-receiver and IR-transmitter 
esphome:
  name: electra-esp-home-ir
  friendly_name: "Electra ESPHome IR"
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  id: api_id
  actions:
    - action: sync_electra_state
      then:
        - lambda: |-
            id(central_ac).sync_state();

ota:
  - platform: esphome
    id: ota_esphome
  - platform: web_server

wifi:
  ssid: "YourWifiName"
  password: "YourWifiPassword"
  ap:

captive_portal:

web_server:
  port: 80
  
network:
  enable_ipv6: true

external_components:
  - source:
      type: git
      url: https://github.com/grymster/ElectraEspHomeIR
      ref: main
    refresh: 0s

sensor:
  - platform: homeassistant
    name: "Temperature"
    id: ac_temperature
    entity_id: sensor.temperature

  - platform: homeassistant
    name: "Humidity"
    id: ac_humidity
    entity_id: sensor.humidity

switch:
  - platform: gpio
    pin: GPIO21
    id: ir_power_21
    name: "IR System Power"
    restore_mode: ALWAYS_ON

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%
  id: ir_tx
  rmt_symbols: 256

remote_receiver:
  id: ir_rx
  pin:
    number: GPIO14
    inverted: true
  rmt_symbols: 256
  dump: all


climate:
  - platform: electra
    name: Central AC
    id: central_ac
    transmitter_id: ir_tx
    receiver_id: ir_rx
    supports_off_command: False
    sensor: ac_temperature
    humidity_sensor: ac_humidity
    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step:
        target_temperature: 1
        current_temperature: 0.1
